/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import GUI.Modales.Modal;
import GUI.Modales.Modal2;
import MySql.Conexiones;
import Objetos.Alumno;
import java.awt.Color;
import java.awt.Font;
import java.awt.Frame;
import java.awt.Window;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import sun.swing.table.DefaultTableCellHeaderRenderer;
/**
 *
 * @author miriam
 */


public class PanelVisualiza extends javax.swing.JPanel {

    
    
    Alumno alumno = new Alumno();
    List <Alumno> datos = new ArrayList<>();
    Conexiones conexion = new Conexiones();
    int id;
    String idS = null;
    
    DefaultTableModel modelo = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int filas, int columnas) {
            if(columnas == 4)
            {
                return true;
            }
            else
            {
                return false;
            }
        }
        
    };

    
    public PanelVisualiza() {
        initComponents();
        
        
         ((DefaultTableCellRenderer) tabla.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(SwingConstants.CENTER);
        tabla.getTableHeader().setFont(new Font("Serif", Font.BOLD, 20));
        tabla.getTableHeader().setOpaque(false);
        tabla.getTableHeader().setBackground(Color.blue); //NO FUNCIONA
        tabla.getTableHeader().setForeground(Color.BLACK);
        tabla.setRowHeight(25);
        
        listallena();
    }
    public void listallena()
    {   
        modelo.setRowCount(0);
        
        modelo.setColumnIdentifiers(new Object[]{"Boleta", "Nombre", "Primer Apellido", "Segundo Apellido"});
        
        conexion.conectar(); //CONECTAR A LA BD
        
        conexion.muestra(); //OBTIENE TODOS LOS REGISTROS DE LA BD
        
        datos = conexion.getLista(); //TRAE DICHOS REGISTROS A LA CLASE ACTUAL
        
        conexion.desconectar(); //CIERRA CONEXION
        
        for(Alumno aux : datos)//FOREACH
        {
            //CREA LAS FILAS
            modelo.addRow(new Object[]{String.valueOf(aux.getMatricula()),aux.getNombre(), aux.getPrimer_apellido(), aux.getSegundo_apellido()});
        }
       
        tabla.setModel(modelo); //AÑADE EL MODELO AL JTABLE CREADO
        
        conexion.limpiaLista(); //LIMPIA LISTA DE LA CLASE Conexiones
        datos.clear();          //LIMPIA LISTA DE LA CLASE ACTUAL
    }
    public void listallenaDinamica()
    {   
        modelo.setRowCount(0);
        
        modelo.setColumnIdentifiers(new Object[]{"Matricula", "Nombre", "Primer Apellido", "Segundo Apellido"}); //CREAR COLUMNAS
        
        conexion.conectar(); //CONECTAR A LA BD
        
        conexion.muestraDinamica(txtSearch.getText()); //OBTIENE TODOS LOS REGISTROS DE LA BD
        
        datos = conexion.getLista(); //TRAE DICHOS REGISTROS A LA CLASE ACTUAL
        
        conexion.desconectar(); //CIERRA CONEXION
        
        for(Alumno aux : datos)//FOREACH
        {
            //CREA LAS FILAS
            modelo.addRow(new Object[]{String.valueOf(aux.getMatricula()),aux.getNombre(), aux.getPrimer_apellido(), aux.getSegundo_apellido()});
        }
       
        tabla.setModel(modelo); //AÑADE EL MODELO AL JTABLE CREADO
        
        conexion.limpiaLista(); //LIMPIA LISTA DE LA CLASE Conexiones
        datos.clear();          //LIMPIA LISTA DE LA CLASE ACTUAL
    }
    
    public void noSelec()
    {
        idS = null;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEliminar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSearch = new rscomponentshade.RSTextFieldShade();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(780, 600));
        setMinimumSize(new java.awt.Dimension(780, 600));
        setPreferredSize(new java.awt.Dimension(780, 600));

        btnEliminar.setBackground(new java.awt.Color(1, 112, 250));
        btnEliminar.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setMaximumSize(new java.awt.Dimension(250, 60));
        btnEliminar.setMinimumSize(new java.awt.Dimension(250, 60));
        btnEliminar.setPreferredSize(new java.awt.Dimension(250, 60));
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarMouseExited(evt);
            }
        });
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Serif", 1, 70)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Visualizar Alumnos");
        jPanel2.add(jLabel1, java.awt.BorderLayout.CENTER);

        txtSearch.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        txtSearch.setMaximumSize(new java.awt.Dimension(450, 60));
        txtSearch.setMinimumSize(new java.awt.Dimension(450, 60));
        txtSearch.setPlaceholder("Buscar Alumno");
        txtSearch.setPreferredSize(new java.awt.Dimension(450, 60));
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchKeyTyped(evt);
            }
        });

        tabla.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Boleta", "Nombre", "Primer Apellido", "Segundo Apellido"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.setFocusable(false);
        tabla.setGridColor(new java.awt.Color(255, 255, 255));
        tabla.setRowHeight(25);
        tabla.setSelectionBackground(new java.awt.Color(1, 112, 250));
        tabla.setShowVerticalLines(false);
        tabla.getTableHeader().setReorderingAllowed(false);
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(295, 295, 295))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseEntered
        btnEliminar.setBackground(new Color(0,160,255));
    }//GEN-LAST:event_btnEliminarMouseEntered

    private void btnEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseExited
        btnEliminar.setBackground(new Color(1,112,250));
    }//GEN-LAST:event_btnEliminarMouseExited

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if(idS != null)
        {
           
           Window parentWindow = SwingUtilities.windowForComponent(this);
           Frame parentframe = null;
           if(parentWindow instanceof Frame)
           {
               parentframe = (Frame)parentWindow;
           }
           Modal m = new Modal(parentframe,true,alumno,2);
           m.setVisible(true);
           if(m.getRespuesta())
           {
               listallena();
               idS = null;
           }
           
        }
        else
        {
           Window parentWindow = SwingUtilities.windowForComponent(this);
           Frame parentframe = null;
           if(parentWindow instanceof Frame)
           {
               parentframe = (Frame)parentWindow;
           }
           Modal2 m = new Modal2(parentframe,true,1);
           m.setVisible(true);
           
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
          id = tabla.rowAtPoint(evt.getPoint());
          
          idS = String.valueOf(tabla.getValueAt(id, 0));
          alumno.setMatricula(Long.parseLong((String) tabla.getValueAt(id, 0)));
          alumno.setNombre(String.valueOf(tabla.getValueAt(id, 1)));
          alumno.setPrimer_apellido(String.valueOf(tabla.getValueAt(id, 2)));
          alumno.setSegundo_apellido(String.valueOf(tabla.getValueAt(id, 3)));
    }//GEN-LAST:event_tablaMouseClicked

    private void txtSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyTyped
        listallenaDinamica();
    }//GEN-LAST:event_txtSearchKeyTyped

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed

    }//GEN-LAST:event_txtSearchKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private rscomponentshade.RSTextFieldShade txtSearch;
    // End of variables declaration//GEN-END:variables

}
